---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-pod-basic
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
  annotations:
    kubernetes.io/description: "For basic pod lifecycle faults"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-pod-exec
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
  annotations:
    kubernetes.io/description: "For pod faults requiring exec"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-stress
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
  annotations:
    kubernetes.io/description: "For pod-level stress faults only"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-network
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
  annotations:
    kubernetes.io/description: "For pod-level network faults only"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-network-policy
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
  annotations:
    kubernetes.io/description: "For network policy-based faults"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-admin
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
  annotations:
    kubernetes.io/description: "For chaos infrastructure orchestration"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-chaos
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
  annotations:
    kubernetes.io/description: "For Argo workflow execution"
