---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-pod-basic
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-pod-exec
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-stress
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-network
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-network-policy
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-node-admin
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-node-restart
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-kubelet-density
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hce-admin
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-chaos
  namespace: hce
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: harness-chaos-engineering
