apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hce-stress-clusterrole
  labels:
    app.kubernetes.io/name: hce
    app.kubernetes.io/component: chaos-clusterrole
    app.kubernetes.io/part-of: harness-chaos-engineering
  annotations:
    kubernetes.io/description: "For both pod-level and node-level stress faults"
rules:
- apiGroups: [""]
  resources: [pods, events, pods/log, pods/exec]
  verbs: [create, delete, get, list, patch, update, deletecollection]
- apiGroups: [""]
  resources: [nodes]
  verbs: [get, list]
- apiGroups: [apps]
  resources: [deployments, statefulsets, replicasets, daemonsets]
  verbs: [get, list]
- apiGroups: [batch]
  resources: [jobs]
  verbs: [create, delete, get, list, deletecollection]
